# Writter: Hiu Sum Yuen
# Version: 1.0

apiVersion: v1
kind: ConfigMap
metadata: 
  name: myconfigmap
data:
  nginx.cfg: |
    upstream backend {
      server app-1:8080;
      server app-2:8080;
    }

    server {
      location / {
        proxy_pass http://backend;
      }
    }
