apiVersion: v1
kind: Pod
metadata:
    name: bluepod
    labels: 
        app: blue
spec:
    containers:
    - name: webpage
      image: docker.io/httpd 
      ports:
        - name: web
          containerPort: 80
          protocol: TCP

